on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

name: 01-rscript

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'  # Specify the R version you need

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "tidyr", "rvest", "data.table", "lubridate", "doParallel", "httr", "sidrar"), repos="https://cran.rstudio.com")'

      - name: Execute Script ipca
        run: |
          Rscript "data/ipca.R"

      - name: Execute Script
        run: |
          Rscript "data/script.R"

      - name: Commit results and push to GitHub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
